//+------------------------------------------------------------------+
//|                                               RiskBasedTrade.mq5 |
//|                                            Generated by :)   |
//+------------------------------------------------------------------+
#property copyright ":)"
#property version   "1.00"

#include <Trade\Trade.mqh>

//+------------------------------------------------------------------+
//| INPUT PARAMETERS                                                 |
//+------------------------------------------------------------------+
// We have replaced the "Lots" inputs with "Money Risk ($)" inputs.
input double InpMoneyRiskLong  = 100.0; // Long Money Risk ($)
input double InpMoneyRiskShort = 100.0; // Short Money Risk ($)

// Global Trade Object
CTrade trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    Print("Risk Based EA Initialized. Long Risk: $", InpMoneyRiskLong, " | Short Risk: $", InpMoneyRiskShort);
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    // --- Example Trading Logic ---
    // Here is where your indicator or price action logic would go.
    // For demonstration, we are just using placeholder boolean variables.
    
    bool signalBuy = false;  // Replace with actual Buy condition
    bool signalSell = false; // Replace with actual Sell condition
    
    if(signalBuy && PositionsTotal() == 0)
    {
        // 1. Calculate Lots based on user's input Money Risk
        double lots = CalculateVolumeByFixedDollar(_Symbol, ORDER_TYPE_BUY, InpMoneyRiskLong);
        
        // 2. Execute Trade if volume is valid
        if(lots > 0)
        {
            trade.Buy(lots, _Symbol);
            Print("Executed BUY. Risked: $", InpMoneyRiskLong, " | Calculated Lots: ", lots);
        }
    }
    
    if(signalSell && PositionsTotal() == 0)
    {
        // 1. Calculate Lots based on user's input Money Risk
        double lots = CalculateVolumeByFixedDollar(_Symbol, ORDER_TYPE_SELL, InpMoneyRiskShort);
        
        // 2. Execute Trade if volume is valid
        if(lots > 0)
        {
            trade.Sell(lots, _Symbol);
            Print("Executed SELL. Risked: $", InpMoneyRiskShort, " | Calculated Lots: ", lots);
        }
    }
}

//+------------------------------------------------------------------+
//| Calculate volume (lots) for fixed dollar exposure                |
//+------------------------------------------------------------------+
double CalculateVolumeByFixedDollar(string symbol, ENUM_ORDER_TYPE order_type, double fixed_dollars)
{
    // Fetch price and contract size
    double price = (order_type == ORDER_TYPE_BUY) ? SymbolInfoDouble(symbol, SYMBOL_ASK) : SymbolInfoDouble(symbol, SYMBOL_BID);
    double contractSize = SymbolInfoDouble(symbol, SYMBOL_TRADE_CONTRACT_SIZE);

    // Guard against division by zero
    if (price <= 0.0 || contractSize <= 0.0) 
    {
        Print("Error: Invalid price or contract size for ", symbol);
        return 0.0;
    }

    // Simplified Calculation: target_money / (price * contractSize)
    double raw_lots = fixed_dollars / (price * contractSize);

    if (raw_lots <= 0.0) return 0.0;

    // Normalize the lot size to broker's volume step and limits
    double step = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);
    double min  = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
    double max  = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX);

    if (step <= 0.0) return NormalizeDouble(raw_lots, 2); 

    // Round down to the nearest allowed volume step
    double normalized_lots = MathFloor(raw_lots / step) * step;

    // Clamp to min boundaries
    if (normalized_lots < min) 
    {
        Print("Warning: Target money ($", fixed_dollars, ") is too low for minimum lot size. Defaulting to minimum.");
        normalized_lots = min; 
    }
    
    // Clamp to max boundaries
    if (normalized_lots > max) 
    {
        normalized_lots = max;
    }

    // Fix floating point imprecision inherent in doubles
    int digits = 0;
    if (step == 0.1) digits = 1;
    else if (step == 0.01) digits = 2;
    else if (step == 0.001) digits = 3;
    else if (step == 0.0001) digits = 4;

    return NormalizeDouble(normalized_lots, digits);
}